### ISSUE TITLE
Plugin doesn't pull account automatically

### ISSUE THREAD

**Issue by vlar** [frank-m/alfred-rdp-workflow#6]
Hello, 

I'm not sure whether it is a bug or intended / missing feature but the tool do initiate a RDP session but asks for the password while it is saved on the RDP app. 
It would be great if there was a way to have it used the default assigned account to the rdp.

**Comment by vlar** [comment]
I have located this answer but I have few further ideas on how to implement that but it should help if there is an intention to implement it 👍 
https://stackoverflow.com/questions/48713606/how-to-create-rdp-file-on-mac-os-that-allows-auto-login

**Comment by frank-m** [comment]
The problem is that I cannot directly call the bookmark in the 'Microsoft Remote Desktop' app. What I do is export the bookmark, which gives me everything but the username/password. Then I run `rdp:// url`, which calls the default rdp program, which is 'Microsoft Remote Desktop' and that opens the url directly.

As such I cannot add users and passwords I am afraid. That will only work if the RDP will allow direct executing of bookmarks from the CLI.
